# Generated by Django 4.0.2 on 2022-02-12 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=15)),
                ('cat_id', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='customer.category')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=25)),
                ('comp_add', models.CharField(max_length=45)),
                ('comp_phone', models.CharField(max_length=10)),
                ('comp_email', models.EmailField(max_length=50)),
                ('contact_person', models.CharField(max_length=45)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.area')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallary_img', models.ImageField(upload_to='Gallary')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('offer_title', models.CharField(default='Not Specified', max_length=20)),
                ('offer_details', models.TextField(max_length=200)),
                ('discount', models.FloatField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.company')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=45)),
                ('price', models.IntegerField()),
                ('qty_on_hand', models.IntegerField()),
                ('discount', models.FloatField(null=True)),
                ('desc', models.TextField()),
                ('product_img', models.ImageField(upload_to='ProductImg/')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.category')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pur_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purRet_date', models.DateField(auto_now=True)),
                ('credit_amt', models.IntegerField()),
                ('pur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.CharField(max_length=45)),
                ('raw_qtyHand', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=25)),
                ('report_date', models.DateField()),
                ('report_file', models.FileField(upload_to='Reports/')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_date', models.DateTimeField(auto_now=True)),
                ('payment_status', models.CharField(max_length=10)),
                ('sales_status', models.CharField(default='pending', max_length=20)),
                ('payment_date', models.DateTimeField()),
                ('is_cancel', models.BooleanField(default=False)),
                ('offer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.offer')),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitOfmes', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UserBase',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('gender', models.BooleanField(default='Not Specified')),
                ('dob', models.DateField(default='Not Specified')),
                ('cus_add1', models.TextField(blank=True, null=True)),
                ('cus_add2', models.TextField(blank=True, null=True)),
                ('pincode', models.IntegerField()),
                ('Cus_phone', models.CharField(max_length=10)),
                ('profile', models.ImageField(max_length=1500, upload_to='profileImages/')),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.area')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup_name', models.CharField(max_length=45)),
                ('sup_add', models.CharField(max_length=200)),
                ('sup_phone', models.CharField(max_length=10)),
                ('sup_email', models.EmailField(max_length=30)),
                ('shop_name', models.CharField(max_length=45)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.area')),
                ('comp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.company')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=15)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.country')),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesRe_date', models.DateField(auto_now=True)),
                ('sales_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.sales')),
            ],
        ),
        migrations.AddField(
            model_name='sales',
            name='userbase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.userbase'),
        ),
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pur_discount', models.FloatField(blank=True, null=True)),
                ('pur_amt', models.IntegerField()),
                ('pur_status', models.CharField(max_length=10)),
                ('purPaymentDate', models.DateTimeField(auto_now=True)),
                ('pur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.purchase')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='sup_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.supplier'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='userbase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.userbase'),
        ),
        migrations.CreateModel(
            name='PurachseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pur_qty', models.IntegerField()),
                ('pur_price', models.IntegerField()),
                ('pur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.purchase')),
                ('raw_matId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.rawmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_qty', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.product')),
                ('raw_matId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.rawmaterial')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='color_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.productcolor'),
        ),
        migrations.AddField(
            model_name='product',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.company'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.productsize'),
        ),
        migrations.CreateModel(
            name='CustomizedProdoct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_productName', models.CharField(max_length=45)),
                ('cus_productImg', models.ImageField(max_length=150, upload_to='CustomizedProduct')),
                ('cus_productDetails', models.TextField()),
                ('cus_productPrice', models.IntegerField()),
                ('color_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.productcolor')),
                ('size_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.productsize')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('com_desc', models.CharField(max_length=200)),
                ('com_date', models.DateField(auto_now=True)),
                ('com_resolve', models.BooleanField(default=False)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.product')),
                ('userbase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.userbase')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=15)),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.state')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.city'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_date', models.DateField()),
                ('app_status', models.BooleanField(default=False)),
                ('app_time', models.TimeField()),
                ('userbase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.userbase')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.product')),
                ('userbase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.userbase')),
            ],
            options={
                'unique_together': {('userbase', 'product_id')},
            },
        ),
        migrations.CreateModel(
            name='SalesReturnDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salRet_qty', models.IntegerField()),
                ('salRet_reason', models.CharField(max_length=200)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.product')),
                ('sales_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.sales')),
            ],
            options={
                'ordering': ['sales_id'],
                'unique_together': {('product_id', 'sales_id')},
            },
        ),
        migrations.CreateModel(
            name='SalesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.product')),
                ('sales_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.sales')),
            ],
            options={
                'ordering': ['-sales_id'],
                'unique_together': {('product_id', 'sales_id')},
            },
        ),
        migrations.CreateModel(
            name='RawMaterialDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_price', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.product')),
                ('raw_matId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.rawmaterial')),
                ('userbase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.userbase')),
            ],
            options={
                'unique_together': {('userbase', 'product_id', 'raw_matId')},
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.product')),
                ('userbase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.userbase')),
            ],
            options={
                'unique_together': {('userbase', 'product_id')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purRet_qty', models.IntegerField()),
                ('purReturn_Reason', models.CharField(max_length=200)),
                ('purRetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.purchasereturn')),
                ('raw_matId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.rawmaterial')),
            ],
            options={
                'unique_together': {('purRetId', 'raw_matId')},
            },
        ),
        migrations.CreateModel(
            name='ProductHasRawMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.product')),
                ('raw_matId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.rawmaterial')),
            ],
            options={
                'unique_together': {('product_id', 'raw_matId')},
            },
        ),
        migrations.CreateModel(
            name='productHasOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.offer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.product')),
            ],
            options={
                'unique_together': {('product_id', 'offer_id')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('size_id', 'id', 'color_id')},
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_title', models.CharField(max_length=45)),
                ('fb_desc', models.TextField()),
                ('fb_date', models.DateTimeField(auto_now=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.product')),
                ('userbase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.userbase')),
            ],
            options={
                'unique_together': {('userbase', 'product_id')},
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_qty', models.IntegerField()),
                ('cart_price', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.product')),
                ('userbase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.userbase')),
            ],
            options={
                'unique_together': {('userbase', 'product_id')},
            },
        ),
    ]
