# Generated by Django 4.0.2 on 2022-02-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_cart_userbase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='sales_date',
            field=models.DateField(auto_now=True),
        ),
    ]
