# Generated by Django 4.0.2 on 2022-02-14 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_sales_sales_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_price',
        ),
    ]
