# Generated by Django 4.0.2 on 2022-02-15 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0005_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='userbase',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(default='None', max_length=6),
        ),
    ]
