# Generated by Django 4.0.2 on 2022-02-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_appointment_app_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='app_status',
            field=models.BooleanField(null=True),
        ),
    ]
