# Generated by Django 4.0.2 on 2022-02-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_appointment_app_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='note',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
