# Generated by Django 3.2.4 on 2022-03-09 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_sales_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='production',
            name='raw_matId',
        ),
        migrations.RemoveField(
            model_name='purchasepayment',
            name='pur_id',
        ),
        migrations.RemoveField(
            model_name='purchasereturn',
            name='pur_id',
        ),
        migrations.AlterUniqueTogether(
            name='purchasereturndetails',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='purchasereturndetails',
            name='purRetId',
        ),
        migrations.RemoveField(
            model_name='purchasereturndetails',
            name='raw_matId',
        ),
        migrations.AlterUniqueTogether(
            name='rawmaterialdetails',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rawmaterialdetails',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='rawmaterialdetails',
            name='raw_matId',
        ),
        migrations.RemoveField(
            model_name='rawmaterialdetails',
            name='userbase',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='raw_qtyHand',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='is_cancel',
        ),
        migrations.AddField(
            model_name='purachsedetails',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.unitofmeasurement'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductHasRawMaterials',
        ),
        migrations.DeleteModel(
            name='Production',
        ),
        migrations.DeleteModel(
            name='PurchasePayment',
        ),
        migrations.DeleteModel(
            name='PurchaseReturn',
        ),
        migrations.DeleteModel(
            name='PurchaseReturnDetails',
        ),
        migrations.DeleteModel(
            name='RawMaterialDetails',
        ),
    ]
