# Generated by Django 3.2.4 on 2022-03-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20220309_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='d_date',
            field=models.DateField(null=True),
        ),
    ]
