# Generated by Django 3.2.4 on 2022-03-17 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesreturndetails',
            options={'ordering': ['sales_ret_id']},
        ),
        migrations.AddField(
            model_name='salesreturndetails',
            name='sales_ret_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='customer.salesreturn'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='salesreturndetails',
            unique_together={('product_id', 'sales_ret_id')},
        ),
        migrations.RemoveField(
            model_name='salesreturndetails',
            name='sales_id',
        ),
    ]
