# Generated by Django 3.2.4 on 2022-03-18 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_auto_20220317_2050'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salesreturndetails',
            unique_together=set(),
        ),
    ]
