# Generated by Django 3.2.4 on 2022-03-18 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_alter_salesreturndetails_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurachseDetails',
            new_name='PurchaseDetails',
        ),
    ]
