# Generated by Django 3.2.9 on 2022-03-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_salesreturndetails_salret_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
    ]
