# Generated by Django 3.2.9 on 2022-03-20 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_auto_20220320_1654'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('userbase', 'product_id')},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('userbase', 'product_id')},
        ),
    ]
