from telnetlib import GA
from django.contrib import admin
from .models import *

# Register your models here.

admin.site.register(Country)
admin.site.register(State)
admin.site.register(City)
admin.site.register(Area)
admin.site.register(Company)
admin.site.register(UserBase)
admin.site.register(Product)
admin.site.register(CustomizedProdoct)
# admin.site.register(Offer)
admin.site.register(Sales)
admin.site.register(SalesDetails)
admin.site.register(SalesReturn)
admin.site.register(SalesReturnDetails)
# admin.site.register(Production)
admin.site.register(Complaint)
admin.site.register(Wishlist)
admin.site.register(Cart)
admin.site.register(ProductColor)
admin.site.register(ProductSize)
admin.site.register(Category)
admin.site.register(Appointment)
admin.site.register(Rating)
admin.site.register(Feedback)
admin.site.register(Supplier)
admin.site.register(RawMaterial)
# admin.site.register(RawMaterialDetails)
# admin.site.register(ProductHasRawMaterials)
admin.site.register(UnitOfMeasurement)
admin.site.register(Purchase)
admin.site.register(PurchaseDetails)
# admin.site.register(PurchasePayment)
# admin.site.register(PurchaseReturn)
# admin.site.register(PurchaseReturnDetails)
# admin.site.register(productHasOffer)
admin.site.register(Gallary)
admin.site.register(reports)
admin.site.register(generateotp)
admin.site.register(Notification)
