from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    # Customer URLS Goes Here...
    path("registration/",views.registration,name="registration"),
    path("registration_2/",views.registration_2,name="registration_2"),
    path("sign-in/",views.signIn,name="sign-in"),
    path("logout_user/",views.logout_user,name="logout_user"),
    path("password/",auth_views.PasswordChangeView.as_view(template_name="change-pass.html"),name="password"),
    path("country_ajax-data/",views.country_ajax_data,name="country_ajax-data"),
    path("c_ajax_data/",views.c_ajax_data,name="c_ajax_data"),
    path("state_ajax-data/",views.state_ajax_data,name="state_ajax-data"),
    path("city_ajax-data/",views.city_ajax_data,name="city_ajax-data"),
    path("area_ajax-data/",views.area_ajax_data,name="area_ajax-data"),
    path("mainAdmin/",views.index,name="index"),
    path("otp/",views.otp,name="otp"),
    # path("test/", views.test,name="test"),


    path("password-reset/", auth_views.PasswordResetView.as_view(template_name="customer/forgot-password.html"),name="password_reset"),
    path("password-change/", auth_views.PasswordResetView.as_view(template_name="customer/change-password.html"),name="password_change"),
    path("password-reset/done/", auth_views.PasswordResetDoneView.as_view(template_name="customer/password-sent.html"),name="password_reset_done"),
    path("password-reset-confirm/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(template_name="accounts/cus_change.html"),name="password_reset_confirm"),
    path("reset_password_complete/", auth_views.PasswordResetCompleteView.as_view(template_name="customer/password-reset-done.html"),name="password_reset_complete"),
    
    #
    path("forgetpass",views.forgetpass,name="forgetpass"),
    path("verifyotp/<int:id>",views.verifyotp,name="verifyotp"),
    path("updateAdminpass/<int:id>",views.updateAdminpass,name="updateAdminpass"),
    path("myorders",views.myorders,name="myorders"),
    path("placeorder",views.placeorder,name="placeorder"),

    # Admin URLS Goes Here...
    path("purchasehistory",views.purchasehistory,name="purchasehistory"),
    path("cancelledorder",views.cancelledorder,name="cancelledorder"),
    path("addrm",views.addrm,name="addrm"),
    path("addcat",views.addcat,name="addcat"),
    path("changepasswordfromold",views.changepasswordfromold,name="changepasswordfromold"),
    path("purDet/<int:id>",views.purDet,name="purDet"),
    path("products/",views.products,name="products"),
    path("addproduct/",views.addProduct,name="addproduct"),
    path("delrecord/<int:id>",views.deleteRecord,name="delrecord"),
    path("cat_ajax-data/",views.cat_ajax_data,name="cat_ajax-data"),
    path("viewproduct/<int:id>",views.viewproduct,name="viewproduct"),
    path("updateproduct/<int:id>",views.updateproduct,name="updateproduct"),
    path("cusproduct/",views.cusProduct,name="cusproduct"),
    path("addcusproduct/",views.addcusproduct,name="addcusproduct"),
    path("viewcus/<int:id>",views.viewcus,name="viewcus"),
    path("delcus/<int:id>",views.delcus,name="delcus"),
    path("customers/",views.customers,name="customers"),
    path("customerdet/<int:id>",views.customerdet,name="customerdet"),
    path("gallary",views.gallary,name="gallary"),
    path("addimage",views.addimage,name="addimage"),
    path("delimg/<int:id>",views.delimg,name="delimg"),
    path("vieworders/",views.vieworders,name="vieworders"),
    path("view_det_orders/<int:id>",views.view_det_orders,name="view_det_orders"),
    path("det_rec_ord/<int:id>",views.det_rec_ord,name="det_rec_ord"),
    path("delrorder/<int:id>",views.delrorder,name="delrorder"),
    path("returnorder",views.returnorder,name="returnorder"),
    path("viewretorders/<int:id>",views.viewretorders,name="viewretorders"),
    path("completeorder/",views.completeorder,name="completeorder"),
    path("viewcomporder/<int:id>",views.viewcomporder,name="viewcomporder"),
    path("appointment",views.appointment,name="appointment"),
    path("complaints",views.complaints,name="complaints"),
    path("rescomp/<int:id>",views.rescomp,name="rescomp"),
    path("sendanswer/<int:id>",views.sendanswer,name="sendanswer"),
    path("filtercomp",views.filtercomp,name="filtercomp"),
    path("feedback",views.feedback,name="feedback"),
    path("viewfeed/<int:fid>/<int:rid>",views.viewfeed,name="viewfeed"),
    path("supplier",views.supplier,name="supplier"),
    path("purchase",views.purchase,name="purchase"),
    path("addsup",views.addsup,name="addsup"),
    path("sendorder/<int:id>",views.sendorder,name="sendorder"),
    path("adminprofile",views.adminprofile,name="adminprofile"),
    path("appointmentResult/<int:id>",views.appointmentResult,name="appointmentResult"),
    path("gen_reports",views.gen_reports,name="gen_reports"),
    path("rp",views.rp,name="rp"),
    path("downloadPdf/<int:id>",views.downloadPdf,name="downloadPdf"),
   path("delReport/<int:id>",views.delReport,name="delReport"),
    path("updateprofile",views.updateprofile,name="updateprofile"),
    path("searchCustomer",views.searchCustomer,name="searchCustomer"),

    # path("delfeed/<int:fid><int:rid>",views.delfeed,name="delfeed"),
    
    
    # Customer URLS
    path("testaudio",views.testaudio,name="testaudio"),
    path("applyfilter",views.applyfilter,name="applyfilter"),
    path("",views.home,name="home"),
    path("womens",views.womens,name="womens"),
    path("myorders",views.myorders,name="myorders"),
    path("aboutus",views.aboutus,name="aboutus"),
    path("cart",views.cart,name="cart"),
    path("wishlist",views.wishlist,name="wishlist"),
    path("userprofile",views.userprofile,name="userprofile"),
    path("edit_profile/<int:id>",views.edit_profile,name="edit_profile"),
    path("single/<str:id>",views.single,name="single"),
    path("userregister",views.userregister,name="userregister"),
    path("userlogout",views.userlogout,name="userlogout"),
    path("userlogin",views.userlogin,name="userlogin"),
    path("usercheck",views.usercheck,name="usercheck"),
    path("emailcheck",views.emailcheck,name="emailcheck"),
    path("comp_data",views.comp_data,name="comp_data"),
    path("addtocart/<str:id>",views.addtocart,name="addtocart"),
    path("saveappp",views.saveappo,name="saveappo"),
    path("removecart/<int:id>",views.removecart,name="removecart"),
    path("removewish/<int:id>",views.removewish,name="removewish"),
    path("addtowish/<int:id>",views.addtowish,name="addtowish"),
    path("checkout",views.checkout,name="checkout"),
    path("catprod",views.catprod,name="catprod"),
    path("saveqty",views.saveqty,name="saveqty"),
    path("makecomp/<int:id>",views.makecomp,name="makecomp"),
    path("view_ord/<int:id>",views.view_ord,name="view_ord"),
    path("searchprod",views.searchprod,name="searchprod"),
    path("cancelsale/<int:id>",views.cancelsale,name="cancelsale"),
    path("delappo/<int:id>",views.delappo,name="delappo"),
    path("addfeed",views.addfeed,name="addfeed"),
    path("savepur",views.savepur,name="savepur"),
    path("addraw",views.addraw,name="addraw"),
    path("delraw/<int:id>",views.delraw,name="delraw"),
    path("addcatt",views.addcatt,name="addcatt"),
    path("addsubcat",views.addsubcat,name="addsubcat"),
    path("delcat/<int:id>",views.delcat,name="delcat"),
    path("deliver/<int:id>",views.deliver,name="deliver"),
    path("noti",views.noti,name="noti"),
    path("readnot",views.readnot,name="readnot"),
    path("returnorder/<int:id>",views.returnorder,name="returnorder"),
    path("downinvoice/<int:id>",views.downinvoice,name="downinvoice"),
    path("delsup/<int:id>",views.delsup,name="delsup"),

    
    
    
    
    

  
]
